# Generated by Django 4.2.5 on 2023-09-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0003_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
