# Generated by Django 4.2.5 on 2023-09-22 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0004_project_user_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('categoria', models.CharField(choices=[('ELECTRONICA', 'ELECTRONICA'), ('INSUMOS', 'INSUMOS'), ('SEGURIDAD', 'SEGURIDAD'), ('TRANSITO', 'TRANSITO'), ('Sin Categoria', 'Sin Categoria')], default='Sin Categoria', max_length=60)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meli_info.items')),
            ],
        ),
    ]
