# Generated by Django 4.2.5 on 2023-09-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0005_items_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='name',
            new_name='item',
        ),
    ]
