# Generated by Django 4.2.5 on 2023-09-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0006_rename_name_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
