# Generated by Django 4.2.5 on 2023-09-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0007_alter_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ultima_mod',
            field=models.DateTimeField(default="2023-09-23 01:43:58.890155"),
            preserve_default=False,
        ),
    ]
