# Generated by Django 4.2.5 on 2023-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0008_inventario_ultima_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='last_item_create',
            field=models.DateTimeField(default="2023-09-23 01:43:58.890155"),
            preserve_default=False,
        ),
    ]
