# Generated by Django 4.2.5 on 2023-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0009_items_last_item_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ultima_mod',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
