# Generated by Django 4.2.5 on 2023-09-23 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0010_alter_inventario_ultima_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ultima_mod',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 2, 3, 32, 323572, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='items',
            name='last_item_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 2, 3, 32, 323572, tzinfo=datetime.timezone.utc)),
        ),
    ]
