# Generated by Django 4.2.5 on 2023-09-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0011_alter_inventario_ultima_mod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meli_info.items', unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ultima_mod',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='last_item_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
