# Generated by Django 4.2.5 on 2023-09-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meli_info', '0013_alter_inventario_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
